-- ============================================================================
-- MEDFLOW - ESQUEMA DO BANCO DE DADOS (POSTGRESQL 15+)
-- 100% EM PORTUGUÊS
-- IDs com tipo BIGINT sequencial (GENERATED BY DEFAULT AS IDENTITY)
-- ============================================================================

-- ============================================================================
-- 1. CLINICAS / EMPRESAS
-- ============================================================================
CREATE TABLE IF NOT EXISTS clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    razao_social VARCHAR(150),
    cnpj VARCHAR(18) UNIQUE,
    telefone VARCHAR(30) NOT NULL,
    email VARCHAR(120) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL DEFAULT -19.922700,
    longitude DOUBLE PRECISION NOT NULL DEFAULT -43.945100,
    foto_logo_url TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_clinicas_email ON clinicas(email);
CREATE INDEX IF NOT EXISTS idx_clinicas_ativo ON clinicas(ativo);

-- ============================================================================
-- 2. ESPECIALIDADES MEDICAS
-- ============================================================================
CREATE TABLE IF NOT EXISTS especialidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    icone VARCHAR(50) DEFAULT 'stethoscope',
    cor VARCHAR(30) DEFAULT 'sage',
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_especialidades_nome ON especialidades(nome);

-- ============================================================================
-- 3. USUARIOS E ACESSOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL CHECK (perfil IN ('paciente', 'medico', 'clinica', 'admin')),
    foto_url TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON usuarios(perfil);

-- ============================================================================
-- 4. PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) UNIQUE,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    email VARCHAR(150) NOT NULL,
    foto_url TEXT,
    contato_emergencia VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pacientes_usuario_id ON pacientes(usuario_id);
CREATE INDEX IF NOT EXISTS idx_pacientes_cpf ON pacientes(cpf);
CREATE INDEX IF NOT EXISTS idx_pacientes_nome ON pacientes(nome);

-- ============================================================================
-- 5. MEDICOS / PROFISSIONAIS DE SAUDE
-- ============================================================================
CREATE TABLE IF NOT EXISTS medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    clinica_id BIGINT REFERENCES clinicas(id) ON DELETE SET NULL,
    especialidade_id BIGINT REFERENCES especialidades(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    primeiro_nome VARCHAR(60),
    crm VARCHAR(40) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    biografia TEXT,
    avaliacao VARCHAR(10) DEFAULT '5,0',
    foto_url TEXT,
    nome_consultorio VARCHAR(150),
    endereco VARCHAR(255),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    horario_inicio TIME NOT NULL DEFAULT '08:00:00',
    horario_fim TIME NOT NULL DEFAULT '18:00:00',
    duracao_consulta_minutos INTEGER NOT NULL DEFAULT 30,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_medicos_usuario_id ON medicos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_medicos_clinica_id ON medicos(clinica_id);
CREATE INDEX IF NOT EXISTS idx_medicos_especialidade_id ON medicos(especialidade_id);
CREATE INDEX IF NOT EXISTS idx_medicos_crm ON medicos(crm);
CREATE INDEX IF NOT EXISTS idx_medicos_coordenadas ON medicos(latitude, longitude);

-- ============================================================================
-- 6. AGENDAS E HORARIOS LIBERADOS DO MEDICO
-- ============================================================================
CREATE TABLE IF NOT EXISTS agendas_medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medico_id BIGINT NOT NULL REFERENCES medicos(id) ON DELETE CASCADE,
    data_agenda DATE NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_medico_data UNIQUE (medico_id, data_agenda)
);

CREATE INDEX IF NOT EXISTS idx_agendas_medico_data ON agendas_medicos(medico_id, data_agenda);

CREATE TABLE IF NOT EXISTS horarios_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL REFERENCES agendas_medicos(id) ON DELETE CASCADE,
    horario VARCHAR(5) NOT NULL, -- 'HH:mm'
    disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agenda_horario UNIQUE (agenda_id, horario)
);

CREATE INDEX IF NOT EXISTS idx_horarios_agenda_disponivel ON horarios_agenda(agenda_id, disponivel);

-- ============================================================================
-- 7. CONSULTAS E AGENDAMENTOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE RESTRICT,
    medico_id BIGINT NOT NULL REFERENCES medicos(id) ON DELETE RESTRICT,
    clinica_id BIGINT REFERENCES clinicas(id) ON DELETE SET NULL,
    data_consulta DATE NOT NULL,
    horario_consulta VARCHAR(5) NOT NULL, -- 'HH:mm'
    status VARCHAR(30) NOT NULL DEFAULT 'Pendente' CHECK (
        status IN ('Pendente', 'Confirmado', 'Compareceu', 'Nao compareceu', 'Em atendimento', 'Concluído', 'Cancelado')
    ),
    tipo VARCHAR(40) NOT NULL DEFAULT 'Primeira consulta',
    motivo TEXT,
    motivo_cancelamento TEXT,
    cancelado_em TIMESTAMP WITH TIME ZONE,
    versao BIGINT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_consultas_paciente ON consultas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_consultas_medico_data ON consultas(medico_id, data_consulta);
CREATE INDEX IF NOT EXISTS idx_consultas_status ON consultas(status);

-- Índice único condicional: impede duplicidade de horário ativo para o mesmo médico
CREATE UNIQUE INDEX IF NOT EXISTS idx_unico_medico_consulta_ativa
ON consultas (medico_id, data_consulta, horario_consulta)
WHERE status != 'Cancelado';

-- ============================================================================
-- 8. PRONTUARIOS MEDICOS E REGISTROS CLINICOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS prontuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES medicos(id) ON DELETE SET NULL,
    resumo TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_prontuario_paciente_medico UNIQUE (paciente_id, medico_id)
);

CREATE INDEX IF NOT EXISTS idx_prontuarios_paciente ON prontuarios(paciente_id);

CREATE TABLE IF NOT EXISTS anotacoes_prontuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios(id) ON DELETE CASCADE,
    nome_autor VARCHAR(150) NOT NULL,
    data_anotacao DATE NOT NULL DEFAULT CURRENT_DATE,
    conteudo TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_anotacoes_prontuario_id ON anotacoes_prontuario(prontuario_id);

CREATE TABLE IF NOT EXISTS procedimentos_prontuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios(id) ON DELETE CASCADE,
    nome_procedimento VARCHAR(200) NOT NULL,
    data_procedimento DATE NOT NULL DEFAULT CURRENT_DATE,
    observacoes TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_procedimentos_prontuario_id ON procedimentos_prontuario(prontuario_id);

CREATE TABLE IF NOT EXISTS documentos_prontuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios(id) ON DELETE CASCADE,
    titulo VARCHAR(200) NOT NULL,
    arquivo_url TEXT,
    nome_arquivo VARCHAR(255),
    tipo_arquivo VARCHAR(50),
    tamanho_bytes BIGINT,
    conteudo_texto TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_documentos_prontuario_id ON documentos_prontuario(prontuario_id);

-- ============================================================================
-- 9. NOTIFICACOES DO SISTEMA
-- ============================================================================
CREATE TABLE IF NOT EXISTS notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES medicos(id) ON DELETE CASCADE,
    titulo VARCHAR(150) NOT NULL,
    mensagem TEXT NOT NULL,
    lida BOOLEAN NOT NULL DEFAULT FALSE,
    lida_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notificacoes_usuario ON notificacoes(usuario_id);

-- ============================================================================
-- 10. TRILHA DE AUDITORIA
-- ============================================================================
CREATE TABLE IF NOT EXISTS eventos_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    acao VARCHAR(100) NOT NULL,
    tipo_recurso VARCHAR(60) NOT NULL,
    recurso_id BIGINT,
    ip_origem VARCHAR(45),
    user_agent TEXT,
    detalhes JSONB,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON eventos_auditoria(usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_criado_em ON eventos_auditoria(criado_em);
