import {
  Heart,
  CalendarDays,
  Clock3,
  Search,
  Bell,
  UserRound,
  UsersRound,
  Stethoscope,
  LayoutDashboard,
  FileText,
  Settings2,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  Check,
  X,
  Plus,
  Sparkles,
  Flower2,
  Apple,
  Activity,
  Brain,
  FlaskConical,
  MapPin,
  Star,
  Menu,
  LogOut,
  SlidersHorizontal,
  Download,
  ShieldCheck,
  ClipboardList,
  ChartNoAxesCombined,
  Mail,
  Phone,
  CircleHelp,
  Camera,
  Upload,
} from 'lucide-react';
const icons = {
  camera: Camera,
  upload: Upload,
  heart: Heart,
  calendar: CalendarDays,
  clock: Clock3,
  search: Search,
  bell: Bell,
  user: UserRound,
  users: UsersRound,
  stethoscope: Stethoscope,
  dashboard: LayoutDashboard,
  file: FileText,
  settings: Settings2,
  right: ChevronRight,
  left: ChevronLeft,
  arrow: ArrowRight,
  back: ArrowLeft,
  check: Check,
  x: X,
  plus: Plus,
  sparkles: Sparkles,
  flower: Flower2,
  apple: Apple,
  activity: Activity,
  brain: Brain,
  flask: FlaskConical,
  pin: MapPin,
  star: Star,
  menu: Menu,
  logout: LogOut,
  filter: SlidersHorizontal,
  download: Download,
  shield: ShieldCheck,
  clipboard: ClipboardList,
  chart: ChartNoAxesCombined,
  mail: Mail,
  phone: Phone,
  help: CircleHelp,
};
export default function Icon({ name, size = 20, ...props }) {
  const Component = icons[name] || Heart;
  return <Component size={size} strokeWidth={1.7} aria-hidden="true" {...props} />;
}
