-- ============================================================================
-- PROJETO MEDFLOW - BANCO DE DADOS COMPLETO (POSTGRESQL 15+)
-- 100% EM PORTUGUÊS (TABELAS, COLUNAS, CHAVES E ÍNDICES)
-- IDs COM TIPO BIGINT (SEQUENCIAIS: 1, 2, 3...)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. CLINICAS / EMPRESAS
-- ============================================================================
CREATE TABLE IF NOT EXISTS clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    razao_social VARCHAR(150),
    cnpj VARCHAR(18) UNIQUE,
    telefone VARCHAR(30) NOT NULL,
    email VARCHAR(120) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL DEFAULT -19.922700,
    longitude DOUBLE PRECISION NOT NULL DEFAULT -43.945100,
    foto_logo_url TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_clinicas_email ON clinicas(email);
CREATE INDEX IF NOT EXISTS idx_clinicas_ativo ON clinicas(ativo);

-- ============================================================================
-- 2. ESPECIALIDADES MEDICAS
-- ============================================================================
CREATE TABLE IF NOT EXISTS especialidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    icone VARCHAR(50) DEFAULT 'stethoscope',
    cor VARCHAR(30) DEFAULT 'sage',
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_especialidades_nome ON especialidades(nome);

-- ============================================================================
-- 3. USUARIOS E ACESSOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL CHECK (perfil IN ('paciente', 'medico', 'clinica', 'admin')),
    foto_url TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON usuarios(perfil);

-- ============================================================================
-- 4. PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) UNIQUE,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    email VARCHAR(150) NOT NULL,
    foto_url TEXT,
    contato_emergencia VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pacientes_usuario_id ON pacientes(usuario_id);
CREATE INDEX IF NOT EXISTS idx_pacientes_cpf ON pacientes(cpf);
CREATE INDEX IF NOT EXISTS idx_pacientes_nome ON pacientes(nome);

-- ============================================================================
-- 5. MEDICOS / PROFISSIONAIS DE SAUDE
-- ============================================================================
CREATE TABLE IF NOT EXISTS medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    clinica_id BIGINT REFERENCES clinicas(id) ON DELETE SET NULL,
    especialidade_id BIGINT REFERENCES especialidades(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    primeiro_nome VARCHAR(60),
    crm VARCHAR(40) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    biografia TEXT,
    avaliacao VARCHAR(10) DEFAULT '5,0',
    foto_url TEXT,
    nome_consultorio VARCHAR(150),
    endereco VARCHAR(255),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    horario_inicio TIME NOT NULL DEFAULT '08:00:00',
    horario_fim TIME NOT NULL DEFAULT '18:00:00',
    duracao_consulta_minutos INTEGER NOT NULL DEFAULT 30,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_medicos_usuario_id ON medicos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_medicos_clinica_id ON medicos(clinica_id);
CREATE INDEX IF NOT EXISTS idx_medicos_especialidade_id ON medicos(especialidade_id);
CREATE INDEX IF NOT EXISTS idx_medicos_crm ON medicos(crm);
CREATE INDEX IF NOT EXISTS idx_medicos_coordenadas ON medicos(latitude, longitude);

-- ============================================================================
-- 6. AGENDAS E HORARIOS LIBERADOS DO MEDICO
-- ============================================================================
CREATE TABLE IF NOT EXISTS agendas_medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medico_id BIGINT NOT NULL REFERENCES medicos(id) ON DELETE CASCADE,
    data_agenda DATE NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_medico_data UNIQUE (medico_id, data_agenda)
);

CREATE INDEX IF NOT EXISTS idx_agendas_medico_data ON agendas_medicos(medico_id, data_agenda);

CREATE TABLE IF NOT EXISTS horarios_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL REFERENCES agendas_medicos(id) ON DELETE CASCADE,
    horario VARCHAR(5) NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agenda_horario UNIQUE (agenda_id, horario)
);

CREATE INDEX IF NOT EXISTS idx_horarios_agenda_disponivel ON horarios_agenda(agenda_id, disponivel);

-- ============================================================================
-- 7. CONSULTAS E AGENDAMENTOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE RESTRICT,
    medico_id BIGINT NOT NULL REFERENCES medicos(id) ON DELETE RESTRICT,
    clinica_id BIGINT REFERENCES clinicas(id) ON DELETE SET NULL,
    data_consulta DATE NOT NULL,
    horario_consulta VARCHAR(5) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Pendente' CHECK (
        status IN ('Pendente', 'Confirmado', 'Compareceu', 'Nao compareceu', 'Em atendimento', 'Concluído', 'Cancelado')
    ),
    tipo VARCHAR(40) NOT NULL DEFAULT 'Primeira consulta',
    motivo TEXT,
    motivo_cancelamento TEXT,
    cancelado_em TIMESTAMP WITH TIME ZONE,
    versao BIGINT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_consultas_paciente ON consultas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_consultas_medico_data ON consultas(medico_id, data_consulta);
CREATE INDEX IF NOT EXISTS idx_consultas_status ON consultas(status);

-- Evita agendamento duplo/concorrente para o mesmo médico, data e horário (se não estiver cancelado)
CREATE UNIQUE INDEX IF NOT EXISTS idx_unico_medico_consulta_ativa
ON consultas (medico_id, data_consulta, horario_consulta)
WHERE status != 'Cancelado';

-- ============================================================================
-- 8. PRONTUARIOS MEDICOS E REGISTROS CLINICOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS prontuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES medicos(id) ON DELETE SET NULL,
    resumo TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_prontuario_paciente_medico UNIQUE (paciente_id, medico_id)
);

CREATE INDEX IF NOT EXISTS idx_prontuarios_paciente ON prontuarios(paciente_id);

CREATE TABLE IF NOT EXISTS anotacoes_prontuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios(id) ON DELETE CASCADE,
    nome_autor VARCHAR(150) NOT NULL,
    data_anotacao DATE NOT NULL DEFAULT CURRENT_DATE,
    conteudo TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_anotacoes_prontuario_id ON anotacoes_prontuario(prontuario_id);

CREATE TABLE IF NOT EXISTS procedimentos_prontuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios(id) ON DELETE CASCADE,
    nome_procedimento VARCHAR(200) NOT NULL,
    data_procedimento DATE NOT NULL DEFAULT CURRENT_DATE,
    observacoes TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_procedimentos_prontuario_id ON procedimentos_prontuario(prontuario_id);

CREATE TABLE IF NOT EXISTS documentos_prontuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios(id) ON DELETE CASCADE,
    titulo VARCHAR(200) NOT NULL,
    arquivo_url TEXT,
    nome_arquivo VARCHAR(255),
    tipo_arquivo VARCHAR(50),
    tamanho_bytes BIGINT,
    conteudo_texto TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_documentos_prontuario_id ON documentos_prontuario(prontuario_id);

-- ============================================================================
-- 9. NOTIFICACOES DO SISTEMA
-- ============================================================================
CREATE TABLE IF NOT EXISTS notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES medicos(id) ON DELETE CASCADE,
    titulo VARCHAR(150) NOT NULL,
    mensagem TEXT NOT NULL,
    lida BOOLEAN NOT NULL DEFAULT FALSE,
    lida_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notificacoes_usuario ON notificacoes(usuario_id);

-- ============================================================================
-- 10. TRILHA DE AUDITORIA
-- ============================================================================
CREATE TABLE IF NOT EXISTS eventos_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    acao VARCHAR(100) NOT NULL,
    tipo_recurso VARCHAR(60) NOT NULL,
    recurso_id BIGINT,
    ip_origem VARCHAR(45),
    user_agent TEXT,
    detalhes JSONB,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON eventos_auditoria(usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_criado_em ON eventos_auditoria(criado_em);

-- ============================================================================
-- CARGA DE DADOS INICIAIS (SEED)
-- ============================================================================

INSERT INTO especialidades (id, nome, descricao, icone, cor) OVERRIDING SYSTEM VALUE VALUES
(1, 'Dermatologia', 'Cuidado e saúde para a sua pele.', 'sparkles', 'rose'),
(2, 'Estética', 'Bem-estar que valoriza você.', 'flower', 'peach'),
(3, 'Nutrição', 'Mais equilíbrio em cada escolha.', 'apple', 'sage'),
(4, 'Fisioterapia', 'Movimento e qualidade de vida.', 'activity', 'blue'),
(5, 'Psicologia', 'Um espaço para se ouvir.', 'brain', 'lavender'),
(6, 'Biomedicina Estética', 'Ciência e cuidado em harmonia.', 'flask', 'rose'),
(7, 'Enfermagem', 'Acolhimento em cada etapa.', 'heart', 'peach'),
(8, 'Clínica Geral', 'Um olhar completo para você.', 'stethoscope', 'sage')
ON CONFLICT (id) DO NOTHING;

INSERT INTO clinicas (id, nome, razao_social, cnpj, telefone, email, endereco, latitude, longitude) OVERRIDING SYSTEM VALUE VALUES
(1, 'Clínica Saúde & Estética', 'MedFlow Saúde Integrada Ltda', '12.345.678/0001-90', '(31) 3333-0000', 'contato@clinica.example', 'Rua das Flores, 120 · Funcionários, Belo Horizonte - MG', -19.922700, -43.945100)
ON CONFLICT (id) DO NOTHING;

INSERT INTO usuarios (id, email, senha_hash, perfil) OVERRIDING SYSTEM VALUE VALUES
(1, 'admin@medflow.example', '$2a$10$e8O0aK77pXJ9i86kR8rWqOU0zHj2aF75d4M92W2n.v7gD21gR67C2', 'clinica'),
(2, 'ana@medflow.example', '$2a$10$e8O0aK77pXJ9i86kR8rWqOU0zHj2aF75d4M92W2n.v7gD21gR67C2', 'medico'),
(3, 'beatriz@medflow.example', '$2a$10$e8O0aK77pXJ9i86kR8rWqOU0zHj2aF75d4M92W2n.v7gD21gR67C2', 'medico'),
(4, 'carlos@medflow.example', '$2a$10$e8O0aK77pXJ9i86kR8rWqOU0zHj2aF75d4M92W2n.v7gD21gR67C2', 'medico'),
(5, 'maria@medflow.example', '$2a$10$e8O0aK77pXJ9i86kR8rWqOU0zHj2aF75d4M92W2n.v7gD21gR67C2', 'paciente'),
(6, 'fernanda@medflow.example', '$2a$10$e8O0aK77pXJ9i86kR8rWqOU0zHj2aF75d4M92W2n.v7gD21gR67C2', 'paciente')
ON CONFLICT (id) DO NOTHING;

INSERT INTO medicos (id, usuario_id, clinica_id, especialidade_id, nome, primeiro_nome, crm, email, telefone, biografia, avaliacao, nome_consultorio, endereco, latitude, longitude) OVERRIDING SYSTEM VALUE VALUES
(1, 2, 1, 1, 'Dra. Ana Silva', 'Dra. Ana', 'CRM 123456/MG', 'ana@medflow.example', '(31) 99999-0001', 'Especialista em dermatologia clínica e estética com foco em saúde da pele.', '4,9', 'Consultório Dra. Ana Silva', 'Rua das Flores, 120, Sala 301 - Funcionários, Belo Horizonte - MG', -19.922700, -43.945100),
(2, 3, 1, 2, 'Dra. Beatriz Lima', 'Dra. Beatriz', 'CRM 123457/MG', 'beatriz@medflow.example', '(31) 99999-0002', 'Procedimentos estéticos avançados e rejuvenescimento facial.', '4,8', 'Espaço Beatriz Estética', 'Av. Afonso Pena, 1500, Sala 804 - Centro, Belo Horizonte - MG', -19.928100, -43.937200),
(3, 4, 1, 3, 'Dr. Carlos Souza', 'Dr. Carlos', 'CRN 12345/MG', 'carlos@medflow.example', '(31) 99999-0003', 'Nutrição esportiva e reeducação alimentar personalizada.', '4,9', 'NutriVida Consultório', 'Rua Sergipe, 1000 - Savassi, Belo Horizonte - MG', -19.938200, -43.935500)
ON CONFLICT (id) DO NOTHING;

INSERT INTO pacientes (id, usuario_id, nome, cpf, data_nascimento, telefone, email) OVERRIDING SYSTEM VALUE VALUES
(1, 5, 'Maria Oliveira', '111.222.333-44', '1990-05-12', '(31) 99999-1001', 'maria@medflow.example'),
(2, 6, 'Fernanda Souza', '222.333.444-55', '1988-11-20', '(31) 99999-1002', 'fernanda@medflow.example')
ON CONFLICT (id) DO NOTHING;

INSERT INTO agendas_medicos (id, medico_id, data_agenda) OVERRIDING SYSTEM VALUE VALUES
(1, 1, CURRENT_DATE),
(2, 1, CURRENT_DATE + INTERVAL '1 day'),
(3, 2, CURRENT_DATE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO horarios_agenda (id, agenda_id, horario, disponivel) OVERRIDING SYSTEM VALUE VALUES
(1, 1, '08:00', TRUE),
(2, 1, '08:30', TRUE),
(3, 1, '09:00', FALSE),
(4, 1, '09:30', TRUE),
(5, 1, '10:00', TRUE),
(6, 1, '14:00', TRUE),
(7, 1, '14:30', TRUE),
(8, 1, '15:00', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO consultas (id, paciente_id, medico_id, clinica_id, data_consulta, horario_consulta, status, tipo, motivo) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 1, 1, CURRENT_DATE, '09:00', 'Confirmado', 'Primeira consulta', 'Gostaria de avaliar manchas no rosto causadas pelo sol.'),
(2, 2, 2, 1, CURRENT_DATE + INTERVAL '1 day', '14:00', 'Pendente', 'Retorno', 'Acompanhamento do protocolo de hidratação e pele.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO prontuarios (id, paciente_id, medico_id, resumo) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 1, 'Paciente em acompanhamento dermatológico preventivo.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO anotacoes_prontuario (id, prontuario_id, nome_autor, conteudo) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 'Dra. Ana Silva', 'Primeira avaliação dermatológica realizada. Solicitado uso diário de protetor solar FPS 50.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO documentos_prontuario (id, prontuario_id, titulo, conteudo_texto) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 'Receituário Dermatológico Inicial', 'Uso contínuo: Filtro solar FPS 50 a cada 3 horas. Hidratante facial calmante à noite.')
ON CONFLICT (id) DO NOTHING;

-- Sincroniza sequências para os próximos inserts continuarem somando (9, 10, 11...)
SELECT setval(pg_get_serial_sequence('especialidades', 'id'), COALESCE(MAX(id), 1)) FROM especialidades;
SELECT setval(pg_get_serial_sequence('clinicas', 'id'), COALESCE(MAX(id), 1)) FROM clinicas;
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), COALESCE(MAX(id), 1)) FROM usuarios;
SELECT setval(pg_get_serial_sequence('medicos', 'id'), COALESCE(MAX(id), 1)) FROM medicos;
SELECT setval(pg_get_serial_sequence('pacientes', 'id'), COALESCE(MAX(id), 1)) FROM pacientes;
SELECT setval(pg_get_serial_sequence('agendas_medicos', 'id'), COALESCE(MAX(id), 1)) FROM agendas_medicos;
SELECT setval(pg_get_serial_sequence('horarios_agenda', 'id'), COALESCE(MAX(id), 1)) FROM horarios_agenda;
SELECT setval(pg_get_serial_sequence('consultas', 'id'), COALESCE(MAX(id), 1)) FROM consultas;
SELECT setval(pg_get_serial_sequence('prontuarios', 'id'), COALESCE(MAX(id), 1)) FROM prontuarios;
SELECT setval(pg_get_serial_sequence('anotacoes_prontuario', 'id'), COALESCE(MAX(id), 1)) FROM anotacoes_prontuario;
SELECT setval(pg_get_serial_sequence('documentos_prontuario', 'id'), COALESCE(MAX(id), 1)) FROM documentos_prontuario;
